# Generated by Django 3.2.6 on 2021-09-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Badge',
            new_name='Badges',
        ),
    ]
