# Generated by Django 3.2.6 on 2021-09-05 05:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0002_rename_guidler_claimed_guilder'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
