# Generated by Django 3.2.5 on 2021-09-07 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0003_badge_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='claimable',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='claimed',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='guilder',
            name='added_on',
        ),
        migrations.AddField(
            model_name='badge',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badge',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='claimable',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claimable',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimable',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='guilder',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guilder',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guilder',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
