# Generated by Django 3.2.6 on 2021-09-08 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0005_auto_20210908_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='claimable',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='claimed',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='guilder',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
